  version: "3.8"
  services:
    node:
      ports:
        - 3000:3000
      image: node:18
      working_dir: /var/www/html
      volumes:
        - ./src:/var/www/html
      command: bash -c "npm run dev"
    database:
      image: mariadb:10.6.10
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
